FROM golang:1.23.3

WORKDIR /my-ebpf-cilium
# COPY ./my-ebpf-cilium my-ebpf-cilium

# clang version 14.0.6
# LLVM version 14
RUN apt-get update && apt-get install -y \
    vim \
    net-tools \
    clang \
    libbpf-dev \
    llvm && rm -rf /var/lib/apt/lists/*

# RUN go mod init ebpf-test

# RUN go mod tidy

# RUN go get github.com/cilium/ebpf/cmd/bpf2go

# RUN go generate

# RUN go build
