/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __HELLOWORLD_BPF_SKEL_H__
#define __HELLOWORLD_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct helloworld_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *rodata_str1_1;
	} maps;
	struct {
		struct bpf_program *bpf_prog;
	} progs;
	struct {
		struct bpf_link *bpf_prog;
	} links;

#ifdef __cplusplus
	static inline struct helloworld_bpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct helloworld_bpf *open_and_load();
	static inline int load(struct helloworld_bpf *skel);
	static inline int attach(struct helloworld_bpf *skel);
	static inline void detach(struct helloworld_bpf *skel);
	static inline void destroy(struct helloworld_bpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
helloworld_bpf__destroy(struct helloworld_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
helloworld_bpf__create_skeleton(struct helloworld_bpf *obj);

static inline struct helloworld_bpf *
helloworld_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct helloworld_bpf *obj;
	int err;

	obj = (struct helloworld_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = helloworld_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	helloworld_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct helloworld_bpf *
helloworld_bpf__open(void)
{
	return helloworld_bpf__open_opts(NULL);
}

static inline int
helloworld_bpf__load(struct helloworld_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct helloworld_bpf *
helloworld_bpf__open_and_load(void)
{
	struct helloworld_bpf *obj;
	int err;

	obj = helloworld_bpf__open();
	if (!obj)
		return NULL;
	err = helloworld_bpf__load(obj);
	if (err) {
		helloworld_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
helloworld_bpf__attach(struct helloworld_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
helloworld_bpf__detach(struct helloworld_bpf *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *helloworld_bpf__elf_bytes(size_t *sz);

static inline int
helloworld_bpf__create_skeleton(struct helloworld_bpf *obj)
{
	struct bpf_object_skeleton *s;
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "helloworld_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 1;
	s->map_skel_sz = sizeof(*s->maps);
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt, s->map_skel_sz);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	s->maps[0].name = ".rodata.str1.1";
	s->maps[0].map = &obj->maps.rodata_str1_1;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "bpf_prog";
	s->progs[0].prog = &obj->progs.bpf_prog;
	s->progs[0].link = &obj->links.bpf_prog;

	s->data = (void *)helloworld_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *helloworld_bpf__elf_bytes(size_t *sz)
{
	*sz = 2056;
	return (const void *)"\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x08\x05\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x0c\0\
\x01\0\xb7\x01\0\0\x21\0\0\0\x6b\x1a\xfc\xff\0\0\0\0\xb7\x01\0\0\x6f\x72\x6c\
\x64\x63\x1a\xf8\xff\0\0\0\0\x18\x01\0\0\x48\x65\x6c\x6c\0\0\0\0\x6f\x2c\x20\
\x57\x7b\x1a\xf0\xff\0\0\0\0\xb7\x01\0\0\x20\x25\x73\x0a\x63\x1a\xe8\xff\0\0\0\
\0\x18\x01\0\0\x70\x66\x5f\x70\0\0\0\0\x72\x6f\x67\x3a\x7b\x1a\xe0\xff\0\0\0\0\
\x18\x01\0\0\x69\x6e\x76\x6f\0\0\0\0\x6b\x65\x20\x62\x7b\x1a\xd8\xff\0\0\0\0\
\xb7\x01\0\0\0\0\0\0\x73\x1a\xec\xff\0\0\0\0\xbf\xa1\0\0\0\0\0\0\x07\x01\0\0\
\xd8\xff\xff\xff\xbf\xa3\0\0\0\0\0\0\x07\x03\0\0\xf0\xff\xff\xff\xb7\x02\0\0\
\x15\0\0\0\x85\0\0\0\x06\0\0\0\xb7\0\0\0\0\0\0\0\x95\0\0\0\0\0\0\0\x48\x65\x6c\
\x6c\x6f\x2c\x20\x57\x6f\x72\x6c\x64\x21\0\x69\x6e\x76\x6f\x6b\x65\x20\x62\x70\
\x66\x5f\x70\x72\x6f\x67\x3a\x20\x25\x73\x0a\0\x44\x75\x61\x6c\x20\x42\x53\x44\
\x2f\x47\x50\x4c\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\x9c\0\0\0\x9c\0\0\0\x06\x01\
\0\0\0\0\0\0\0\0\0\x02\0\0\0\0\0\0\0\0\x01\0\0\x0d\x03\0\0\0\x01\0\0\0\x01\0\0\
\0\x05\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\x09\0\0\0\x01\0\0\x0c\x02\0\0\0\
\xdd\0\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x05\0\0\0\
\x07\0\0\0\x0d\0\0\0\xe2\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\xf6\0\0\0\0\0\0\
\x0e\x06\0\0\0\x01\0\0\0\xfe\0\0\0\x01\0\0\x0f\0\0\0\0\x08\0\0\0\0\0\0\0\x0d\0\
\0\0\0\x63\x74\x78\0\x69\x6e\x74\0\x62\x70\x66\x5f\x70\x72\x6f\x67\0\x74\x72\
\x61\x63\x65\x70\x6f\x69\x6e\x74\x2f\x73\x79\x73\x63\x61\x6c\x6c\x73\x2f\x73\
\x79\x73\x5f\x65\x6e\x74\x65\x72\x5f\x65\x78\x65\x63\x76\x65\0\x2f\x68\x6f\x6d\
\x65\x2f\x76\x61\x67\x72\x61\x6e\x74\x2f\x6c\x61\x62\x2f\x68\x65\x6c\x6c\x6f\
\x77\x6f\x72\x6c\x64\x2f\x68\x65\x6c\x6c\x6f\x77\x6f\x72\x6c\x64\x2e\x62\x70\
\x66\x2e\x63\0\x69\x6e\x74\x20\x62\x70\x66\x5f\x70\x72\x6f\x67\x28\x76\x6f\x69\
\x64\x20\x2a\x63\x74\x78\x29\x20\x7b\0\x20\x20\x20\x20\x63\x68\x61\x72\x20\x6d\
\x73\x67\x5b\x5d\x20\x3d\x20\x22\x48\x65\x6c\x6c\x6f\x2c\x20\x57\x6f\x72\x6c\
\x64\x21\x22\x3b\0\x20\x20\x20\x20\x62\x70\x66\x5f\x70\x72\x69\x6e\x74\x6b\x28\
\x22\x69\x6e\x76\x6f\x6b\x65\x20\x62\x70\x66\x5f\x70\x72\x6f\x67\x3a\x20\x25\
\x73\x5c\x6e\x22\x2c\x20\x6d\x73\x67\x29\x3b\0\x20\x20\x20\x20\x72\x65\x74\x75\
\x72\x6e\x20\x30\x3b\0\x63\x68\x61\x72\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\
\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x4c\x49\x43\x45\x4e\x53\x45\0\x6c\
\x69\x63\x65\x6e\x73\x65\0\0\0\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\x14\0\0\0\x14\0\
\0\0\x6c\0\0\0\x80\0\0\0\0\0\0\0\x08\0\0\0\x12\0\0\0\x01\0\0\0\0\0\0\0\x04\0\0\
\0\x10\0\0\0\x12\0\0\0\x06\0\0\0\0\0\0\0\x37\0\0\0\x65\0\0\0\0\x18\0\0\x08\0\0\
\0\x37\0\0\0\x7f\0\0\0\x0a\x1c\0\0\x40\0\0\0\x37\0\0\0\xa1\0\0\0\x05\x20\0\0\
\x90\0\0\0\x37\0\0\0\0\0\0\0\0\0\0\0\xa8\0\0\0\x37\0\0\0\xa1\0\0\0\x05\x20\0\0\
\xb8\0\0\0\x37\0\0\0\xcf\0\0\0\x05\x24\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x14\0\
\0\0\x12\0\x03\0\0\0\0\0\0\0\0\0\xc8\0\0\0\0\0\0\0\x71\0\0\0\x11\0\x05\0\0\0\0\
\0\0\0\0\0\x0d\0\0\0\0\0\0\0\xac\0\0\0\0\0\0\0\x04\0\0\0\x03\0\0\0\x2c\0\0\0\0\
\0\0\0\x04\0\0\0\x01\0\0\0\x40\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x50\0\0\0\0\0\
\0\0\x04\0\0\0\x01\0\0\0\x60\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x70\0\0\0\0\0\0\
\0\x04\0\0\0\x01\0\0\0\x80\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x90\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\x0b\x0c\0\x2e\x74\x65\x78\x74\0\x2e\x72\x65\x6c\x2e\x42\
\x54\x46\x2e\x65\x78\x74\0\x62\x70\x66\x5f\x70\x72\x6f\x67\0\x2e\x6c\x6c\x76\
\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\x74\x72\x61\x63\x65\x70\x6f\x69\x6e\x74\
\x2f\x73\x79\x73\x63\x61\x6c\x6c\x73\x2f\x73\x79\x73\x5f\x65\x6e\x74\x65\x72\
\x5f\x65\x78\x65\x63\x76\x65\0\x6c\x69\x63\x65\x6e\x73\x65\0\x2e\x73\x74\x72\
\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\0\
\x4c\x49\x43\x45\x4e\x53\x45\0\x2e\x72\x6f\x64\x61\x74\x61\x2e\x73\x74\x72\x31\
\x2e\x31\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x58\0\
\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x7a\x04\0\0\0\0\0\0\x88\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\
\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2b\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\xc8\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x79\0\0\0\x01\0\0\0\x32\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x08\x01\0\0\0\0\0\0\x23\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x01\0\
\0\0\0\0\0\0\x50\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2b\x01\0\0\
\0\0\0\0\x0d\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x6c\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x38\x01\0\0\0\0\0\0\xba\
\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x68\0\0\0\
\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xf8\x03\0\0\0\0\0\0\x10\0\0\0\0\0\
\0\0\x0b\0\0\0\x06\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x0b\0\0\0\x01\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xf4\x02\0\0\0\0\0\0\xa0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x07\0\0\0\x09\0\0\0\x40\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x08\x04\0\0\0\0\0\0\x70\0\0\0\0\0\0\0\x0b\0\0\0\x08\0\0\0\
\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x1d\0\0\0\x03\x4c\xff\x6f\0\0\0\x80\0\0\0\
\0\0\0\0\0\0\0\0\0\x78\x04\0\0\0\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x60\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x98\x03\0\0\0\0\0\0\x60\0\0\0\0\0\0\0\x01\0\0\0\x02\0\0\0\x08\0\0\0\0\0\0\0\
\x18\0\0\0\0\0\0\0";
}

#ifdef __cplusplus
struct helloworld_bpf *helloworld_bpf::open(const struct bpf_object_open_opts *opts) { return helloworld_bpf__open_opts(opts); }
struct helloworld_bpf *helloworld_bpf::open_and_load() { return helloworld_bpf__open_and_load(); }
int helloworld_bpf::load(struct helloworld_bpf *skel) { return helloworld_bpf__load(skel); }
int helloworld_bpf::attach(struct helloworld_bpf *skel) { return helloworld_bpf__attach(skel); }
void helloworld_bpf::detach(struct helloworld_bpf *skel) { helloworld_bpf__detach(skel); }
void helloworld_bpf::destroy(struct helloworld_bpf *skel) { helloworld_bpf__destroy(skel); }
const void *helloworld_bpf::elf_bytes(size_t *sz) { return helloworld_bpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
helloworld_bpf__assert(struct helloworld_bpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __HELLOWORLD_BPF_SKEL_H__ */
